version: '3'
services:
    model:
        build: .
        container_name: clf
        volumes:
            - ./:/tf/classifier/
        ports:
            - 6006:6006
            - 8888:8888
        # runtime: nvidia
        environment:
            FLASK_DEBUG: 1
            ROOTDIR: /tf/classifier
